project_id = "ejmgpxrypogmhgoqpilf"

[functions.reclassify-customers]
verify_jwt = false

[functions.print-agent-token]
verify_jwt = false

[functions.print-agent-auth]
verify_jwt = false

[functions.create-whatsapp-draft-order]
verify_jwt = false
